###  3.10 矩阵与线性代数运算

实际场景中通常需要进行矩阵以及线性代数的运算，比如矩阵乘法、寻求行列式、求解线性方程组等等

numpy 库提供了矩阵martix 对象来解决矩阵相关的问题，同时提供了numpy.linalg子包来实现常见的线性代数运算

In [1]:
import numpy as np

In [2]:
m = np.matrix([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [4]:
#求矩阵的转置
m.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [5]:
#求矩阵的逆
import numpy.linalg

In [8]:
#需要判断m是不是奇异juzhen
if not numpy.linalg.det(m):
    m[1,1] += 10
print(m)
print(m.I)

[[ 1  2  3]
 [ 4 15  6]
 [ 7  8  9]]
[[-0.725      -0.05        0.275     ]
 [-0.05        0.1        -0.05      ]
 [ 0.60833333 -0.05       -0.05833333]]


In [9]:
#求两个矩阵的乘积
v = np.matrix([[2],
               [3],
               [4]])

In [10]:
m * v

matrix([[20],
        [77],
        [74]])

可以在numpy.linalg 子包中找到更多的操作函数，比如：

In [11]:
#求矩阵行列式的值
numpy.linalg.det(m)

-119.99999999999997

In [12]:
#求矩阵的特征值，即|A-lamdaE|X = 0
numpy.linalg.eigvals(m)

array([ 20.77488948,  -1.08730313,   5.31241365])

In [13]:
#求解矩阵  solve for x in mx = v
x = numpy.linalg.solve(m,v)

In [14]:
x

matrix([[ -5.00000000e-01],
        [ -2.12919484e-17],
        [  8.33333333e-01]])

当需要进行矩阵或者线性代数的计算时，显然numpy会是一个非常强大的工具。如果有时间，建议可以好好的研究下numpy的各种用法