###  3.9大型数组运算

涉及到数组的重量级运算操作，可以实用Numpy库，NumPy的一个主要特性是它会给python 提供一个数组对象，相比标准的Python列表会更加适合用来做数学运算。

下面举个小例子：

In [1]:
x = [1,2,3,4]
y = [5,6,7,8]

In [2]:
x*2

[1, 2, 3, 4, 1, 2, 3, 4]

x * 2 在 python 中的list 操作代表了 x + x ，就是将两个数组首尾拼接在一起

In [4]:
x + y

[1, 2, 3, 4, 5, 6, 7, 8]

In [1]:
import numpy as np

In [6]:
ax = np.array([1,2,3,4])
ay = np.array([5,6,7,8])

In [7]:
ax * 2

array([2, 4, 6, 8])

In [8]:
ax + 10

array([11, 12, 13, 14])

In [9]:
ax + ay

array([ 6,  8, 10, 12])

正如所见，两种方案中数组的基本数学运算结果并不相同。特别的，Numpy中的标量运算（ax * 2 或者 ax + 10）会作用在每一个元素上，另外，当两个操作数都是数组的时候执行元素对等位置计算，并最终生成一个新的数组。


对整个数组中所有元素同时执行数学运算可以使得整个数组上的函数运算简单而快捷。比如，如果你想计算多项式的值，可以这样做：

In [10]:
def f(x):
    return 3*x**2 - 2*x + 7

In [11]:
f(ax)

array([ 8, 15, 28, 47])

NumPy 还为数组操作提供了大量的通用函数，这些函数可以作为math 模块中类似的函数代替。例如：

In [12]:
np.sqrt(ax)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [13]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

这里cos(ax) 会默认数组中的是角度值，实际运算中通常需要转化为真实的角度值

在底层实现中，Numpy数组使用了C或者Fortran语言的机制分配内存。也就是说，他们是一个非常大的连续的并且由同类型数据组成的内存区域。所以可用他构造一个比普通python大的多的数组。

关于NumPy有一点需要注意的是，他扩展了Python列表的索引功能。特别是对于多维数组。
例如：

In [2]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [3]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
#取二维矩阵的第一行
a[0]

array([1, 2, 3, 4])

In [8]:
#取a的一个子矩阵
#1:3表示取第二行到第三行（左闭右开）
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [11]:
#对a的某一部分进行操作
a[1:3,1:3] += 10

In [12]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [13]:
#对a的每一行执行一个对应位置的向量加操作
a + [100,100,100,100]

array([[101, 102, 103, 104],
       [105, 116, 117, 108],
       [109, 120, 121, 112]])

In [15]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [16]:
#设定每个元素的最大值等
#当a<10时，取a，否则取10
np.where(a<10,a,10)

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

Numpy是 Python领域中很多科学与工程库的基础，同时也是被广泛使用的最大，最复杂的模块。

通常我们导入numpy时会使用 import Numpy as np,这样操作会节省很多时间

更多信息可以查询NumPY文档，该库的用法值得每个Python程序员去仔细研读。 http://www.numpy.org